format = """
[╭─── ](bold green)$directory$all$character"""

scan_timeout = 10
command_timeout = 200

[character]
success_symbol = "[╰──→](bold green)"
error_symbol = "[╰─ ](bold green)[↯](bold red)"
vimcmd_symbol = "[╘╣ ↹](bold green)"
vimcmd_replace_one_symbol = "[╘╣](bold green)[ ↹](bold purple)"
vimcmd_visual_symbol = "[╘╣](bold green)[ ⇵](bold yellow)"

